name: gym_app
description: METAH GYM Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Shared Preferences
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  
  # Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  
  # Firebase
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.4.0
  firebase_messaging: ^15.2.4
  
  # JSON
  json_annotation: ^4.8.1

dependency_overrides:
  flutter_local_notifications: 17.2.4
  timezone: 0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png